// frontend/src/components/ui/TopButtonContainer.svelte
<div class="flex p-2 gap-1">
    <button class="btn btn-xs btn-outline">File</button>
    <button class="btn btn-xs btn-outline">Edit</button>
    <button class="btn btn-xs btn-outline">View</button>
    <button class="btn btn-xs btn-outline">Playback</button>
    <button class="btn btn-xs btn-outline">Library</button>
    <button class="btn btn-xs btn-outline">Help</button>
</div>

// frontend/src/components/ui/TopButtonContainer.vue
﻿<template>
  <div>
    <button class="btn btn-xs btn-ghost">File</button>
    <button class="btn btn-xs btn-ghost">Edit</button>
    <button class="btn btn-xs btn-ghost">View</button>
    <button class="btn btn-xs btn-ghost">Playback</button>
    <button class="btn btn-xs btn-ghost">Library</button>
    <button class="btn btn-xs btn-ghost">Help</button>
  </div>
</template>
