// frontend/src/App.vue
<script setup lang="ts">
import TopButtonContainer from "@/components/ui/TopButtonContainer.vue";
import PlaybackButtonsContainer from "@/components/playback/PlaybackButtonsContainer.vue";
import VolumeControl from "@/components/playback/VolumeControl.vue";
import ProgressBar from "@/components/playback/ProgressBar.vue";
import PlaylistTabs from "@/components/ui/PlaylistTabs.vue";
import BottomStats from "@/components/ui/BottomStats.vue";
</script>

<template>
  <main>
    <div class="app-container">
      <div class="main-content">
          <div class="flex items-center gap-2">
            <TopButtonContainer />
            <PlaybackButtonsContainer />
            <VolumeControl />
          </div>
        <ProgressBar />
        <PlaylistTabs />
      </div>
      <BottomStats />
    </div>
  </main>
</template>

<style>
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
  overflow: hidden;
}

.main-content {
  flex: 1;
  display: flex;
  flex-direction: column;
  min-height: 0;
  gap: 0.5rem;
}
</style>

<!--<script lang="ts" setup>-->
<!--import {reactive} from 'vue'-->
<!--import {Greet} from '../wailsjs/go/main/App'-->

<!--const data = reactive({-->
<!--  name: "",-->
<!--  resultText: "Please enter your name below 👇",-->
<!--})-->

<!--function greet() {-->
<!--  Greet(data.name).then((result: string) => {-->
<!--    data.resultText = result-->
<!--  })-->
<!--}-->

<!--</script>-->

<!--<template>-->
<!--  <main>-->
<!--    <div class="flex justify-center items-center">-->
<!--      <div class="card">-->
<!--        <div id="result" class="result">{{ data.resultText }}</div>-->
<!--        <div id="input" class="input-box">-->
<!--          <input id="name" v-model="data.name" autocomplete="off" class="input" type="text"/>-->
<!--          <button class="btn btn-xs sm:btn-sm md:btn-md lg:btn-lg xl:btn-xl" @click="greet">Greet</button>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </main>-->
<!--</template>-->

// frontend/src/App.svelte
<script lang="ts">
  import ProgressBar from "./components/playback/ProgressBar.svelte";
  import PlaylistTabs from "./components/ui/PlaylistTabs.svelte";
  import BottomStats from "./components/ui/BottomStats.svelte";
  import PlayBackButtons from "./components/playback/PlaybackButtonContainer.svelte";
  import TopButtonContainer from "./components/ui/TopButtonContainer.svelte";
  import VolumeControl from "./components/playback/VolumeControl.svelte";

  let myTabs: Tab[] = $state([
    {
      id: "tab1",
      label: "First Tab",
      content: {
        title: "Welcome",
        text: "This is the first tab content",
      },
    },
    {
      id: "tab2",
      label: "Second Tab",
      content: {
        title: "Welcome",
        text: "This is the second tab content",
      },
    },
  ]);

  function createTab() {
    myTabs = [
      ...myTabs,
      {
        id: "tab" + (myTabs.length + 1),
        label: "Tab " + (myTabs.length + 1),
        content: {
          title: "Welcome",
          text: "This is tab " + (myTabs.length + 1) + " content",
        },
      },
    ];
  }

  function removeTab(id: string) {
    myTabs = myTabs.filter((tab) => tab.id !== id);
  }

  function renameTab(id: string, newName: string) {
    myTabs = myTabs.map((tab) =>
      tab.id === id ? { ...tab, label: newName } : tab,
    );
  }

  const currentBottomStats = {
    codec: "WavPack",
    bitrate: "998 kbps",
    frequency: "44100 Hz",
    channelType: "stereo",
    playtime: "1:58 / 4:14",
  };
</script>

<div class="app-container">
  <div class="main-content">
    <div class="flex">
      <TopButtonContainer />
      <PlayBackButtons />
      <VolumeControl />
    </div>

    <ProgressBar />
    <PlaylistTabs
      tabs={myTabs}
      onCreateTab={createTab}
      onRemoveTab={removeTab}
      onRenameTab={renameTab}
      class="flex-1 min-h-0"
    />
  </div>
  <BottomStats {currentBottomStats} />
</div>

<style>
  .app-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    overflow: hidden;
  }

  .main-content {
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
    gap: 0.5rem;
  }
</style>
